//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ditecProject_Kushan_E161088
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int sno { get; set; }
        public decimal AccountNo { get; set; }
        public string NIC { get; set; }
        public Nullable<decimal> OldBalance { get; set; }
        public string Mode { get; set; }
        public Nullable<decimal> DipAmount { get; set; }
        public string Date { get; set; }
    }
}
